development:
  adapter: postgresql
  database: weather-development
  pool: 50
  timeout: 5000
  min_messages: warning

test:
  adapter: postgresql
  database: weather-test
  pool: 50
  timeout: 5000
  min_messages: warning

production:
  adapter: postgresql
  database: weather-production
  pool: 50
  timeout: 5000
